import { NextResponse } from "next/server";
import { readFileSync, readdirSync } from "fs";
import path from "path";
export const runtime="nodejs"; export const dynamic="force-dynamic";
function chunks(){const d=path.join(process.cwd(),"data");let fs:string[]=[];try{fs=readdirSync(d).filter(f=>f.endsWith(".txt"))}catch{return []}const out:{source:string;text:string}[]=[];for(const f of fs){readFileSync(path.join(d,f),"utf8").split(/\n\s*\n/).forEach((t,i)=>{if(t.trim())out.push({source:`${f}#para${i}`,text:t.trim()})})}return out}
function retrieve(q:string,k=5){const terms=new Set((q.toLowerCase().match(/[a-z0-9']+/g)||[]).filter(t=>t.length>2));return chunks().map(c=>({c,score:[...terms].filter(t=>c.text.toLowerCase().includes(t)).length})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,Math.min(Math.max(k,1),10))}
export async function GET(){return NextResponse.json({status:"ok",service:"knust-rag-gar",chunks:chunks().length})}
export async function POST(req:Request){try{const b=await req.json();const q=String(b?.question||"").trim();if(!q)return NextResponse.json({detail:"question is required"},{status:400});
const modalUrl=process.env.MODAL_RAG_API_URL?.replace(/\/$/,"");
if(modalUrl){try{const r=await fetch(`${modalUrl}/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,top_k:Number(b?.top_k)||5}),cache:"no-store"});if(r.ok){const data=await r.json();return NextResponse.json(data)}console.error("Modal RAG",r.status)}catch(e){console.error("Modal RAG unavailable",e)}}
const m=retrieve(q,Number(b?.top_k)||5),context=m.map(x=>x.c.text).join("\n\n---\n\n"),sources=m.map(x=>x.c.source);if(!context)return NextResponse.json({answer:"I couldn't find that in the KNUST knowledge base. Please check the official KNUST source for current information.",sources:[]});const token=process.env.HF_TOKEN;if(!token)return NextResponse.json({answer:context,sources,mode:"retrieval-only"});const model=process.env.HF_MODEL||"Qwen/Qwen2.5-7B-Instruct";const prompt=`You are the KNUST E-Learning Centre AI Assistant. Answer only from the supplied KNUST knowledge. Do not invent dates, fees, requirements, policies or links. If the context does not answer the question, say the information is not available.\n\nKNOWLEDGE:\n${context}\n\nQUESTION:\n${q}\n\nANSWER:`;const r=await fetch("https://router.huggingface.co/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"user",content:prompt}],temperature:.2,max_tokens:500})});if(!r.ok){console.error("HF inference",r.status,(await r.text()).slice(0,500));return NextResponse.json({answer:context,sources,mode:"retrieval-fallback"})}const j=await r.json(),answer=j?.choices?.[0]?.message?.content?.trim();return NextResponse.json({answer:answer||context,sources,mode:answer?"hf-inference":"retrieval-fallback"})}catch(e){console.error(e);return NextResponse.json({detail:"Internal server error"},{status:500})}}